### ISSUE TITLE
the default value for 'getlist' can't be a list

### ISSUE THREAD

**Issue by dzen** [Polyconseil/getconf#12]
the doc says:

    allowed_hosts = config.getlist('django.allowed_hosts', ['*'])

but the argument must be a string which will be parsed afterwards:
https://github.com/Polyconseil/getconf/blob/2ea6628df069a37584ef09d5b0654e30f04c4e8a/getconf/base.py#L164

Imho, to have a pythonic API, the default argument must be of the type asked so as to getbool, getfloat ...

**Comment by vperron** [comment]
Closed with #13
