### ISSUE TITLE
AssetionError if default is set for get and getstr method

### ISSUE THREAD

**Issue by vividvilla** [Polyconseil/getconf#21]
Getting `AssertionError` If I set default value for `get` and `getstr` methods. 

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    print config.get('DEBUG', 'ABC')
  File "/Users/vivek/zerodha/test/getconf/getconf/base.py", line 206, in get
    ), 'get("%s", %s) has an invalid default value type.' % (key, repr(default))
AssertionError: get("DEBUG", 'ABC') has an invalid default value type.
```

I am using python 2.7.10 and here is my system info

`sys.version_info(major=2, minor=7, micro=10, releaselevel='final', serial=0)`

It works on Python 3. seems unicode issue

**Comment by rbarrois** [comment]
Hi,

It looks like you're providing a default value as ``bytes`` (Python2's ``str``), whereas ``get()`` / ``getstr()`` will provide ``text`` (Py3's ``str``, Py2's ``unicode``).

An easy fix is to add ``from __future__ import unicode_literals`` to the top of your file.
