### ISSUE TITLE
Make "get()" able to raise ValueError

### ISSUE THREAD

**Issue by Noxy** [Polyconseil/getconf#8]
When the "key" argument can't be found, "get" method fail silently by returning the default argument of "default" parameter. (which is the empty string)
If my "key" can't be found and that I didn't provide the "default" parameter, I would prefer getconf to raise a ValueError.

May I implement this ?

**Comment by dzen** [comment]
imho, get() should not raises, as it must behave as dict's method.

maybe, CONFIG['key'] should ?



2015-01-12 17:47 GMT+01:00 Cédric Bache <notifications@github.com>:

> When the "key" argument can't be found, "get" method fail silently by
> returning the default argument of "default" parameter. (which is the empty
> string)
> If my "key" can't be found and that I didn't provide the "default"
> parameter, I would prefer getconf to raise a ValueError.
>
> May I implement this ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Polyconseil/getconf/issues/8>.
>



-- 
*Benoît CALVEZ*
*Polyconseil* | 26 rue de Berri | 75008 Paris

**Comment by rbarrois** [comment]
One of the goals while designing getconf was that it could handle situations where "the application works in demo mode without providing any configuration".

The proposed feature would remove that option, since an explicit value would have to be provided for each option.

The API also reflects the ``.get()`` method of dictionnaries, which do *not* raise errors; thus, users of ``getconf`` don't expect ``config.get('my.key')`` to raise an exception if the key isn't defined.


Could you provide an example of a situation where this feature would be useful?

The current implementation would be:
```python
if not config.get('db.host'):
    raise ConfigurationError("Please provide a database host.")
```

**Comment by Noxy** [comment]
Let's say I'm doing something like this:
```python
address = config.get('address')
do_something_with(address)
```

If I forgot to provide the key "address" to my config, then I will have an error somewhere in my function "do_something_with", while it would have been much more explicit to have it on the "get" line.
Of course, I can raise an error myself, just like you did in your example. But, I was looking for something more proficient.

**Comment by rbarrois** [comment]
Could you provide a more concrete, real-world example?

Basically, what would the program in the above example do? How is this ``address`` used?

**Comment by rbarrois** [comment]
@Noxy Have you had time to think about this feature request?

**Comment by Noxy** [comment]
I agree with the fact we don't expect "get()" method to raise an error. Dzen was right, I was looking for something like magic method "__getitem__()". 

What i could do is to provide every "default" argument of "get()" method with my dictionary.This would raise an error, but it would be a bit redundant. 
```python
address = config.get('address', default_config['address'])
``` 

If I provide the "default" argument of getconf.__init__() with a default dictionary config, it won't raise an error if I request a field that is not in that default dictionary. 
```python
default_dict = {'foo': 42}
getconf.__init__(default=default_dict)
getconf.get('address')  # Return None without raising.
```

I think I should simply check the default dictionary that I provide.
