### ISSUE TITLE
Load particular files from a directory

### ISSUE THREAD

**Issue by barryib** [Polyconseil/getconf#9]
When using ``ansible`` to deploy a new configuration, ``ansible`` will create backups of the files it plans to update.
Here, this would be ``/path/to/file.ini.20150218``, which *will* be loaded by ``getconf``.

I'd like ``getconf`` to only load ``*.ini`` files.

(original french message below)
> Lorsqu'ansible déploie une configuration il cré systématiquement un backup des fichiers à modifier. Dans le cas de la configuration, il cré un fichier `SINAME.ini.DATE` ce qui peut poser problème si on charge tous les fichiers d'un répertoire.
>
> Il ne faudrait donc charger que les fichiers `*.ini`

**Comment by rbarrois** [comment]
Hi @barryib !

I've translated your request to english: this is a public project.

``getconf`` has no opinion over the name of files it loads; we could tell it to ignore files starting with a ``.``, but it won't restrict itself to ``.ini`` extensions.

**Comment by barryib** [comment]
Thanks @rbarrois I didn't realize that it was a public repo.

By the way, is it possible to do this kind of call `config = getconf.ConfigGetter('/etc/myproj/*.ini')`? In that way, we could load only particular files from a directory.

Skipping hidden files is also a good point.
